# https://golangci-lint.run/docs/configuration/file/
version: "2"
linters:
  exclusions:
    warn-unused: true
    paths:
      - "examples/.*\\.go$"
      - "_test\\.go"
formatters:
  enable:
    - gofmt
    - goimports
