name: Build and test
on:
  workflow_call:
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Install go compiler
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
      - name: Verify go.mod
        run: "go mod tidy && git diff --exit-code"
      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Fetch stable-diffusion release
        id: sd_release
        run: echo "file_content=$(cat stable_diffusion.release)" >> $GITHUB_OUTPUT
      - name: Clone stable-diffusion.cpp
        uses: actions/checkout@v6
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
          ref: ${{ steps.sd_release.outputs.file_content }}
          path: sd
      - name: Build stable-diffusion.cpp
        run: |
          mkdir -p builds/cpu
          cmake -B builds/cpu \
            -DSD_BUILD_SHARED_LIBS=ON \
            -DSD_BUILD_SHARED_GGML_LIB=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSD_BUILD_EXAMPLES=OFF \
            -DSD_WEBP=OFF \
            -DSD_WEBM=OFF \
            -DGGML_AVX2=ON
          time cmake --build builds/cpu --config Release -j$(nproc)
        working-directory: ./sd
      - name: Fetch stable-diffusion .so root
        run: |
          mv sd/builds/cpu/bin/* .
          rm -rf sd
          echo "GOSD_DYN_LIB=$(realpath .)" >> $GITHUB_ENV
      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          which ffmpeg
          ffmpeg -version
      - name: Create swap
        run: |
          sudo fallocate -l 20GB /modelSwap
          sudo chmod  600 /modelSwap
          sudo mkswap /modelSwap
          sudo swapon /modelSwap
      - name: Download test models
        run: |
          python3 -m pip install huggingface_hub
          python3 .github/scripts/download_ci_models.py
      - name: Run tests and print coverages
        run: |
          LD_LIBRARY_PATH=$GOSD_DYN_LIB:$LD_LIBRARY_PATH \
          go test -v -coverprofile=coverage.out "$(go list ./... | grep -v "examples")"
          go tool cover -func=coverage.out
