name: "macOS"
on:
  push:
    branches:
      - main
    paths:
      - '.github/**.yaml'
      - 'pkg/gosd/**.go'
      - 'go.mod'
      - 'go.sum'
      - 'stable_diffusion.release'
jobs:
  macos:
    uses: ./.github/workflows/setup.yaml
    with:
      os: unix
      runner_type: macos-latest
      arch: arm
