name: "Test PRs"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/**.yaml'
      - 'pkg/gosd/**.go'
      - 'go.mod'
      - 'go.sum'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os_name: unix
            runner: ubuntu-latest
          - os_name: win
            runner: windows-latest
          - os_name: unix
            runner: macos-latest
    uses: ./.github/workflows/setup.yaml
    with:
      os: ${{ matrix.os_name }}
      runner_type: ${{ matrix.runner }}
