name: "Test PRs"
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Install go compiler
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Verify go.mod
        run: "go mod tidy && git diff --exit-code"
      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Fetch stable-diffusion release
        id: sd_release
        run: echo "file_content=$(cat stable_diffusion.release)" >> $GITHUB_OUTPUT
      - name: Clone stable-diffusion.cpp
        uses: actions/checkout@v6
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
          ref: ${{ steps.sd_release.outputs.file_content }}
          path: sd
      - name: Build stable-diffusion.cpp
        run: |
          mkdir -p builds/cpu
          cmake -B builds/cpu \
            -DSD_BUILD_SHARED_LIBS=ON \
            -DSD_BUILD_SHARED_GGML_LIB=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSD_BUILD_EXAMPLES=OFF \
            -DSD_WEBP=OFF \
            -DSD_WEBM=OFF \
            -DGGML_AVX2=ON
          time cmake --build builds/cpu --config Release -j$(nproc)
        working-directory: ./sd
      - name: Fetch stable-diffusion .so root
        run: |
          mv sd/builds/cpu/bin/* .
          rm -rf sd
          echo "GOSD_DYN_LIB=$(realpath .)" >> $GITHUB_ENV
      - name: Print memory
        run: |
          df -hT
          lsblk -fs
          free -h
      - name: Download test models
        run: |
          wget --quiet \
            https://huggingface.co/unsloth/FLUX.2-klein-4B-GGUF/resolve/main/flux-2-klein-4b-Q4_K_M.gguf?download=true \
            -O flux-2-klein-4b-Q4_K_M.gguf
          wget --quiet \
            https://huggingface.co/ai-toolkit/flux2_vae/resolve/main/ae.safetensors \
            -O ae.safetensors
          wget --quiet \
            https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf \
            -O Qwen3-4B-Q4_K_M.gguf
          echo "DIFFUSION_MODEL_PATH=$(realpath flux-2-klein-4b-Q4_K_M.gguf)" >> $GITHUB_ENV
          echo "VAE_PATH=$(realpath ae.safetensors)" >> $GITHUB_ENV
          echo "LLM_PATH=$(realpath Qwen3-4B-Q4_K_M.gguf)" >> $GITHUB_ENV

          wget --quiet \
            https://huggingface.co/calcuis/wan-1.3b-gguf/resolve/main/wan2.1-fun-control-1.3b-q4_0.gguf \
            -O wan2.1-fun-control-1.3b-q4_0.gguf
          wget --quiet \
            https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors \
            -O ae.safetensors
          wget --quiet \
            https://huggingface.co/city96/umt5-xxl-encoder-gguf/resolve/main/umt5-xxl-encoder-Q3_K_S.gguf \
            -O umt5-xxl-encoder-Q3_K_S.gguf

          echo "VIDEO_DIFFUSION_MODEL_PATH=$(realpath wan2.1-fun-control-1.3b-q4_0.gguf)" >> $GITHUB_ENV
          echo "VIDEO_VAE_PATH=$(realpath ae.safetensors)" >> $GITHUB_ENV
          echo "VIDEO_T5XXL_PATH=$(realpath umt5-xxl-encoder-Q3_K_S.gguf)" >> $GITHUB_ENV
      - name: Print memory
        run: |
          df -hT
          lsblk -fs
          free -h
          ls -alF $DIFFUSION_MODEL_PATH
          ls -alF $VAE_PATH
          ls -alF $LLM_PATH
          sudo fallocate -l 20GB /modelSwap
          sudo chmod  600 /modelSwap
          sudo mkswap /modelSwap
          sudo swapon /modelSwap
      - name: Run tests and print coverages
        run: |
          LD_LIBRARY_PATH=$GOSD_DYN_LIB:$LD_LIBRARY_PATH \
          go test -v -coverprofile=coverage.out "$(go list ./... | grep -v "examples")"
          go tool cover -func=coverage.out
