name: "Windows"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**.yaml'
      - 'pkg/gosd/**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-11, windows-11-arm]
    uses: ./.github/workflows/setup.yaml
    with:
      os: win
      runner_type: ${{ matrix.runner }}
