name: "Windows"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**.yaml'
      - 'pkg/gosd/**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_name: win
            runner: windows-2022
            arch: amd
          - os_name: win
            runner: windows-11-arm
            arch: arm
    uses: ./.github/workflows/setup.yaml
    with:
      os: win
      runner_type: ${{ matrix.runner }}
      arch: ${{ matrix.arch }}
