name: "Windows"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**.yaml'
      - 'pkg/gosd/**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  linux:
    uses: ./.github/workflows/setup.yaml
    with:
      os: windows-latest
      runner_type: win
